# -----------------------------------------------------
# Monitor Setup
# name: "Default"
# -----------------------------------------------------

monitor=DP-1,1920x1080@360.11,5467x2000,1.0
monitor=DP-2,3840x2160@60.0,2907x1753,1.5
monitor=HDMI-A-1,1920x1080@60.0,7387x1333,1.0
monitor=HDMI-A-1,transform,3
